name: Checkout and setup
description: Simple GitHub Action that checks out the repository and sets up the environment.
inputs:
  secrets:
    description: 'Secrets required for `setup` action.'
    required: false
  variables:
    description: 'Non-secret variables required for `setup` action.'
    required: false
  ref:
    description: "Git ref to checkout. Maps to the `ref` argument to `actions/checkout@v4`."
    required: false
    
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        ref: ${{ inputs.ref }}
    - name: Setup environment
      uses: ./.github/actions/setup
      with:
        secrets: ${{ inputs.secrets }}
        variables: ${{ inputs.variables }}
